### ISSUE TITLE
Event Forwarder Hipchat notifier sends messages not notifications

### ISSUE THREAD

**Issue by jorgepi** [appscode/kubed#260]
I have kubed up and running on a test environment. I'm using it for sending cluster event notifications to Hipchat. The Hipchat Room is receiving the messages but not notifications (room notifications are in Loud mode).

Here the config file:

clusterName: platform-eu
eventForwarder:
  receivers:
  - notifier: Hipchat
    to:
    - Kubernetes Notifications
  rules:
  # notify for warning events in kube-system namespace
  - namespaces:
    - kube-system
    operations:
    - CREATE
    resources:
    - group: "" # core API group
      resources:
      - events
  # notify for both CREATE and DELETE operations in any namespace
  - resources:
    - group: ""  # core API group
      resources:
      - namespaces
      - secrets
      - services
      - serviceaccounts
      - nodes
      - persistentvolumes
      - persistentvolumeclaims
    - group: batch
      resources:
      - jobs
      - cronjobs
    - group: storage.k8s.io
      resources:
      - storageclasses
    - group: extensions
      resources:
      - ingresses
    - group: voyager.appscode.com
      resources:
      - ingresses
    - group: certificates.k8s.io
      resources:
      - certificatesigningrequests
notifierSecretName: hipchat-token

**Comment by jorgepi** [comment]
Anyone know how to configure the Event Forwarder to configure the Hipchat type of messages and notification message colours?

**Comment by jorgepi** [comment]
I have created an issue on the "go-notifier" repo to find options to set the Hipchat notification options: https://github.com/appscode/go-notify/issues/27

**Comment by jorgepi** [comment]
@tamalsaha Shall we vendor this appscode/go-notify#27 in kubed and use it? Thanks in advance. :)

**Comment by tamalsaha** [comment]
The next step will be to revendor and write a doc. I found something here: https://github.com/reactiflux/discord-irc/wiki/Creating-a-discord-bot-&-getting-a-token

**Comment by tamalsaha** [comment]
I have revendored the go-notify library.

**Comment by jorgepi** [comment]
Thanks @tamalsaha I'm testing the hipchat room notifications adding to the container the environment variables "HIPCHAT_NOTIFY=true" and "HIPCHAT_COLOR=ColorGreen" but unfortunately nothing changed.
I also added the new options to the config file but no success:

`eventForwarder:`
  `receivers:`
  `-` `notifier:` Hipchat
    `to:`
    `-` `Kubernetes` `Notifications`
    `Color:` `"ColorGreen"`
    `Notify:` `true`

Am I doing something wrong? How can apply the changes to set to true 'notify' option and set the color of the messages to 'green'?

**Comment by tamalsaha** [comment]
Did you build the docker image for kubed and use that?

**Comment by jorgepi** [comment]
I didn't. I am going to build it, push to our private docker registry and use it.

**Comment by jorgepi** [comment]
@tamalsaha If I deploy the kubed image from the source appscode/kubed:0.6.0-rc.0 on my k8s cluster it still fails. Here part of my yaml:

    spec:
      serviceAccountName: kubed-sa
      containers:
      - name: operator
        image: appscode/kubed:0.6.0-rc.0
        imagePullPolicy: Always
        env:
          - name: HIPCHAT_NOTIFY
            value: 'true'
          - name: HIPCHAT_COLOR
            value: "ColorGreen"

I also built/compiled a new kubed binary file (from the updated repo) and I built a new docker image overwriting the binary:

`FROM appscode/kubed:0.6.0-rc.0`
`COPY files/kubed /usr/bin/kubed`

but the execution fails with this error message:

**kubed flag redefined: log_dir
panic: kubed flag redefined: log_dir**
goroutine 1 [running]:
flag.(*FlagSet).Var(0xc4200c0000, 0x405fc00, 0xc4200b24a0, 0x29fdb66, 0x7, 0x2a484f6, 0x2f)
        /usr/local/Cellar/go/1.10.1/libexec/src/flag/flag.go:810 +0x540
flag.(*FlagSet).StringVar(0xc4200c0000, 0xc4200b24a0, 0x29fdb66, 0x7, 0x0, 0x0, 0x2a484f6, 0x2f)
        /usr/local/Cellar/go/1.10.1/libexec/src/flag/flag.go:713 +0x8b
flag.(*FlagSet).String(0xc4200c0000, 0x29fdb66, 0x7, 0x0, 0x0, 0x2a484f6, 0x2f, 0xc4200b2490)
        /usr/local/Cellar/go/1.10.1/libexec/src/flag/flag.go:726 +0x8b
flag.String(0x29fdb66, 0x7, 0x0, 0x0, 0x2a484f6, 0x2f, 0x63bc71)
        /usr/local/Cellar/go/1.10.1/libexec/src/flag/flag.go:733 +0x69

When you said "build the docker image for kubed" you meant to do any of my previous options?

**Comment by tamalsaha** [comment]
@jorgepi , can you try with the new 0.7.0-rc.0 release? The image should be `appscode/kubed:0.7.0-rc.0` . Sorry that it took me sometime to get working.

**Comment by jorgepi** [comment]
@tamalsaha No problem and thanks for helping me with this. I updated the image version in my deployment yaml file but it is still not working as I expected. Yellow color messages (no notification). Here my configs:

For the deployment:

```
spec:
  serviceAccountName: kubed-sa
  containers:
  - name: operator
    image: appscode/kubed:0.7.0-rc.0
    imagePullPolicy: Always
    env:
      - name: HIPCHAT_NOTIFY
        value: 'true'
      - name: HIPCHAT_COLOR
        value: "ColorGreen"
```

Kubed config file:

```
eventForwarder:
receivers:
- notifier: Hipchat
to:
- Kubernetes Notifications
Color: "ColorGreen"
Notify: true
```

**Comment by tamalsaha** [comment]
Can you set `HIPCHAT_COLOR` to `yellow` ? From hipchat client, the valid values are: https://github.com/appscode/go-notify/blob/17078f08a5bafdaaa93a7bdef2d689326bd57b3a/vendor/github.com/tbruyelle/hipchat-go/hipchat/hipchat.go#L78

**Comment by jorgepi** [comment]
@tamalsaha Yellow is the color of messages sent by default. If I set `HIPCHAT_COLOR` to `green` messages are sent in yellow anyway what means it is not behaving as we expect.

**Comment by tamalsaha** [comment]
@jorgepi , you need to provide this information in the notifier-config secret. I have updated docs here: https://github.com/appscode/kubed/blob/0.7.0-rc.2/docs/guides/cluster-events/notifiers.md#hipchat

Sorry that I am not able to test this. We used to use Hipchat. But we got upgraded to Stride 3 weeks ago. Our old hipchat is now readonly. FWIW, we have added support for Stride, once you also get upgraded.

Let me know if this fixes this issue.

**Comment by jorgepi** [comment]
@tamalsaha I did provide the notifier-config secret. I'm following the documentation but I still don't see the new changes applied. I show you here my configs in Kubernetes:

**Kubed config file:**
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubed-config
  namespace: kubed
data:
  config.yaml: |
    clusterName: platform-eu
    eventForwarder:
      receivers:
      - notifier: Hipchat
        to:
        - Kubernetes Notifications
      rules:
      # notify for warning events in kube-system namespace
      - namespaces:
        - kube-system
        operations:
        - CREATE
        resources:
        - group: "" # core API group
          resources:
          - events
      # notify for both CREATE and DELETE operations in any namespace
      - resources:
        - group: ""  # core API group
          resources:
          - namespaces
          - secrets
          - services
          - serviceaccounts
          - nodes
          - persistentvolumes
          - persistentvolumeclaims
        - group: batch
          resources:
          - jobs
          - cronjobs
        - group: storage.k8s.io
          resources:
          - storageclasses
        - group: extensions
          resources:
          - ingresses
        - group: voyager.appscode.com
          resources:
          - ingresses
        - group: certificates.k8s.io
          resources:
          - certificatesigningrequests
    notifierSecretName: hipchat-token
```

**Hipchat auth token secret:**
```
---
apiVersion: v1
kind: Secret
metadata:
 name: hipchat-token
 namespace: kubed
type: Opaque
data:
 HIPCHAT_AUTH_TOKEN: xxxxxxxxxxxxxxxxxxxxxxxxxxx
```

**Kubernetes deployment:**
```
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kubed-operator
  namespace: kubed
  labels:
    app: kubed
  initializers:
    pending: []
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubed
  template:
    metadata:
      labels:
        app: kubed
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      serviceAccountName: kubed-sa
      containers:
      - name: operator
        image: appscode/kubed:0.7.0-rc.2
        imagePullPolicy: Always
        env:
          - name: HIPCHAT_NOTIFY
            value: "true"
          - name: HIPCHAT_COLOR
            value: "green"
        args:
        - run
        - --v=3
        - --secure-port=8443
        - --audit-log-path=-
        - --tls-cert-file=/var/serving-cert/tls.crt
        - --tls-private-key-file=/var/serving-cert/tls.key
        - --ops-address=:56790
        ports:
        - containerPort: 8443
        - containerPort: 56790
        volumeMounts:
        - name: config
          mountPath: /srv/kubed
        - name: scratch
          mountPath: /tmp
        - mountPath: /var/serving-cert
          name: serving-cert
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
      volumes:
      - name: config
        configMap:
          name: kubed-config
      - name: scratch
        emptyDir: {}
      - name: serving-cert
        secret:
          defaultMode: 420
          secretName: kubed-apiserver-cert
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
```
It looks like the app it's ignoring the Hipchat environment variables for the color and notifications because the messages (no notification) arriving to Hipchat are in yellow color.

<img width="481" alt="screen shot 2018-05-31 at 10 30 20" src="https://user-images.githubusercontent.com/13312131/40774513-b3cb4d0e-64bd-11e8-9d33-c5c747174d73.png">
