### ISSUE TITLE
kubed is using too much memory

### ISSUE THREAD

**Issue by JulienBalestra** [appscode/kubed#304]
Hi everyone,

We are currently using kubed to keep configmaps in sync accross several namespaces.
We’re not using the recycle bin or event forwarding features, only the config syncer.

We hit the following issue: kubed uses too much memory.

On a 8GB machine, the kubed process used almost 6GB.
The size of the cluster is around 300 nodes.

**Comment by dkirrane** [comment]
Any update here hitting same issue eating up 3.5GB

**Comment by tamalsaha** [comment]
@dkirrane, can you take a profile of your running system and share? Please see my previous comment on how to do that.

**Comment by nachomillangarcia** [comment]
Hi! Here is a heap dump, attached to this comment. I took it after 5 min of restarting kubed. My cluster's size is 20 nodes and around 600 pods.


[dump.txt](https://github.com/appscode/kubed/files/2400436/dump.txt)

**Comment by dkirrane** [comment]
@niclic I assume for #327 you use resource limits to workaround this issue i.e. kubed pod gets killed when it goes above limits? What resource limits do you set?

**Comment by niclic** [comment]
@dkirrane 

Sorry for the late response. Yes, the kubed container appears to regularly get killed. The initial resources we added are shown below. I figure there is no ideal memory limit to apply since kubed is likely to keep consuming memory until the problem is resolved. This just makes sure the process is kept in check.

```yaml
resources:
  requests:
    cpu: "50m"
    memory: "128Mi"
  limits:
    cpu: "100m"
    memory: "256Mi"
```

![Screen Shot 2019-03-12 at 12 06 43 PM](https://user-images.githubusercontent.com/1152011/54216072-6080b200-44bf-11e9-80ba-b5a5c1d9e2ae.png)

**Comment by sebastiansirch** [comment]
We also observed that our kubed pod (version 0.9.0) consumes ~14GB of RAM.

**Comment by tamalsaha** [comment]
Client-go for k8s 1.14 release has fixed a memory leak that will also affect kubed https://github.com/kubernetes/kubernetes/pull/74636 . Bug: https://github.com/kubernetes/kubernetes/issues/73587

**Comment by tamalsaha** [comment]
Can you folks try the new 0.10.0 release? It includes the memory leak fix in client-go.

**Comment by tamalsaha** [comment]
I have been running the latest 0.10.0 release in a minikube cluster for last 6 hours.  The cpu and memory seems to be stable. Can you any of you foks test and confirm whether this issue is resolved or not?

**Comment by sebastiansirch** [comment]
I deployed 0.10.0 to our cluster and after 4 minutes, the log shows
```
I0424 09:01:54.708956       1 operator.go:569] Stopping kubed controller
I0424 09:01:56.008357       1 secure_serving.go:156] Stopped listening on [::]:8443
```
due to failed health checks

```
  Warning  Unhealthy  1m               kubelet, nbslx507  Liveness probe failed: Get https://10.42.3.76:8443/healthz: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  6s (x3 over 1m)  kubelet, nbslx507  Liveness probe failed: Get https://10.42.3.76:8443/healthz: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  4s (x4 over 1m)  kubelet, nbslx507  Readiness probe failed: Get https://10.42.3.76:8443/healthz: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**Comment by tamalsaha** [comment]
@sebastiansirch, which cloud provider are you using? How large and active is this cluster? Are you just seeing health check issues or this is actually high memory usage resulting in dead pod?

Is there any way get access to this cluster or may be re-create this a cluster so that I can debug this further?

**Comment by sebastiansirch** [comment]
On-Premise, Rancher/RKE, 9 Nodes, not too much traffic. Unfortunately, remote access is not possible. I only saw the failed health checks and then reverted to v0.9.0.

**Comment by tamalsaha** [comment]
Can you share the kubed config file used for your cluster?

**Comment by sebastiansirch** [comment]
I found my mistake, I had an old value for the tag-attribute in my values.yaml of the helm chart. Kubed is now running and I can observe the memory usage for a few days

**Comment by tamalsaha** [comment]
Thanks @sebastiansirch . Let me know how it goes.

**Comment by tamalsaha** [comment]
@sebastiansirch, how is cpu/memory usage graph look at your end?

**Comment by sebastiansirch** [comment]
We experienced further crashes as described here https://github.com/appscode/kubed/issues/343

However, there also seems to be memory issues:
```
$ kubectl top pod kubed-kubed-dbb66578d-n7pq7 -n kube-system
NAME                          CPU(cores)   MEMORY(bytes)
kubed-kubed-dbb66578d-n7pq7   56m          9443Mi
```
9 GB  seems to be extremely too much für kubed ;-) The graph also indicates a memory leak

![image](https://user-images.githubusercontent.com/5097197/56947675-2a11fb80-6b2e-11e9-96e4-e76d20f1220a.png)

**Comment by hossainemruz** [comment]
@sebastiansirch what version of Kubed are you using? We have released a new version which expect to fix this issue. ref: https://github.com/appscode/kubed/releases

**Comment by sebastiansirch** [comment]
appscode/kubed:0.10.0

**Comment by hossainemruz** [comment]
Well, then the problem might be somewhere else than the one we have fixed. We will take a look as soon as possible. In the meantime, please use resource limit for `kubed-operator` Deployment like @niclic https://github.com/appscode/kubed/issues/304#issuecomment-472067364 to avoid such huge memory consumption. You can easily do it using helm installation process. Ref: https://github.com/appscode/kubed/blob/3c46813dca17244b1d18a636cf5080e5c78dca4a/chart/kubed/values.yaml#L48

**Comment by discostur** [comment]
also seeing abnormal high memory usage - more than 40 GB!

https://pasteboard.co/ImfmmKe.png

seeing the following stack trace - nil pointer difference:

``` 
	/go/src/github.com/appscode/kubed/pkg/recyclebin/recycle_bin.go:115 +0x9c
github.com/appscode/kubed/pkg/operator.(*Operator).RunTrashCanCleaner.func1()
	/go/src/github.com/appscode/kubed/pkg/operator/operator.go:462 +0x2e
github.com/appscode/kubed/vendor/github.com/robfig/cron.FuncJob.Run(0xc0009ce2d0)
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:92 +0x25
github.com/appscode/kubed/vendor/github.com/robfig/cron.(*Cron).runWithRecovery(0xc000184460, 0x63ad840, 0xc0009ce2d0)
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:165 +0x57
created by github.com/appscode/kubed/vendor/github.com/robfig/cron.(*Cron).run
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:199 +0x749
I0703 06:50:08.000525       1 log.go:172] cron: panic running job: runtime error: invalid memory address or nil pointer dereference
goroutine 14532720 [running]:
github.com/appscode/kubed/vendor/github.com/robfig/cron.(*Cron).runWithRecovery.func1(0xc000184460)
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:161 +0x9e
panic(0x243d260, 0x7daefc0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/appscode/kubed/pkg/recyclebin.(*RecycleBin).Cleanup(0xc000ac30b0, 0xc8937e4790, 0x42c8af)
	/go/src/github.com/appscode/kubed/pkg/recyclebin/recycle_bin.go:115 +0x9c
github.com/appscode/kubed/pkg/operator.(*Operator).RunTrashCanCleaner.func1()
	/go/src/github.com/appscode/kubed/pkg/operator/operator.go:462 +0x2e
github.com/appscode/kubed/vendor/github.com/robfig/cron.FuncJob.Run(0xc0009ce2d0)
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:92 +0x25
github.com/appscode/kubed/vendor/github.com/robfig/cron.(*Cron).runWithRecovery(0xc000184460, 0x63ad840, 0xc0009ce2d0)
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:165 +0x57
created by github.com/appscode/kubed/vendor/github.com/robfig/cron.(*Cron).run
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:199 +0x749
I0703 07:50:08.000452       1 log.go:172] cron: panic running job: runtime error: invalid memory address or nil pointer dereference
goroutine 14549600 [running]:
github.com/appscode/kubed/vendor/github.com/robfig/cron.(*Cron).runWithRecovery.func1(0xc000184460)
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:161 +0x9e
panic(0x243d260, 0x7daefc0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/appscode/kubed/pkg/recyclebin.(*RecycleBin).Cleanup(0xc000ac30b0, 0xc7e984bf90, 0x42c8af)
	/go/src/github.com/appscode/kubed/pkg/recyclebin/recycle_bin.go:115 +0x9c
github.com/appscode/kubed/pkg/operator.(*Operator).RunTrashCanCleaner.func1()
	/go/src/github.com/appscode/kubed/pkg/operator/operator.go:462 +0x2e
github.com/appscode/kubed/vendor/github.com/robfig/cron.FuncJob.Run(0xc0009ce2d0)
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:92 +0x25
github.com/appscode/kubed/vendor/github.com/robfig/cron.(*Cron).runWithRecovery(0xc000184460, 0x63ad840, 0xc0009ce2d0)
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:165 +0x57
created by github.com/appscode/kubed/vendor/github.com/robfig/cron.(*Cron).run
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:199 +0x749
I0703 08:50:08.000450       1 log.go:172] cron: panic running job: runtime error: invalid memory address or nil pointer dereference
goroutine 14566517 [running]:
github.com/appscode/kubed/vendor/github.com/robfig/cron.(*Cron).runWithRecovery.func1(0xc000184460)
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:161 +0x9e
panic(0x243d260, 0x7daefc0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/appscode/kubed/pkg/recyclebin.(*RecycleBin).Cleanup(0xc000ac30b0, 0xc000fc2f90, 0x42c8af)
	/go/src/github.com/appscode/kubed/pkg/recyclebin/recycle_bin.go:115 +0x9c
github.com/appscode/kubed/pkg/operator.(*Operator).RunTrashCanCleaner.func1()
	/go/src/github.com/appscode/kubed/pkg/operator/operator.go:462 +0x2e
github.com/appscode/kubed/vendor/github.com/robfig/cron.FuncJob.Run(0xc0009ce2d0)
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:92 +0x25
github.com/appscode/kubed/vendor/github.com/robfig/cron.(*Cron).runWithRecovery(0xc000184460, 0x63ad840, 0xc0009ce2d0)
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:165 +0x57
created by github.com/appscode/kubed/vendor/github.com/robfig/cron.(*Cron).run
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:199 +0x749
```

**Comment by tamalsaha** [comment]
Hello folks,
I am curious to understand what you are using kubed for?

- Take backup of cluster yamls?
- Sync secrets / configmaps?
- search your cluster?

When I started the project, I needed various individual tasks to be done. Instead of writing a separate tool for each one of them ( and filling up the cluster with operators and controllers), I created this project as a kitchen sink for all those tools that don't fit with anything else. I called the project `kube-DEE` as in Kubernetes Daemon. 

As things have progressed, there are various limitations to the original approach. One of the primary limitations is the rise of CRDs. This project needs to be re-written using dynamic clients to support CRDs that we can't know ahead of time.

The cluster backup option had its own limitations around how to clean up old backups. So, we introduced a plugin mechanism to our github.com/stashed project and added support cluster backup https://github.com/stashed/cluster (to be released soon). This uses restic.net under the hood for encrypted, deduplicated backups and uses restic's support for retention policy to clean up old backup.

Originally we needed some support to cleanup old data from InfluxDB (for monitoring) and Elasticsearch (for logging). I don't think InfluxDB is used much. And for Elasticsearch, you might even use curator.

We had some features around watching events. I think it is still useful. But I would probably want to pass the notifications to Prometheus Alertmanager and let it do the routing/silencing/alerting etc, if I were to do this today. Also, once the Kubernetes Dynamic Audit webhook hits beta, we probably should use that instead of the Lister/Watcher mechanism to generate events.

The search engine functionality is something we want to see. But it needs rework to ensure it supports any type of resource and CRDs and it enforces the AuthZ using SubjectReview apis.

The configmap and secret syncer feature is still useful.

So, can you please tell me how you are using this project and what do you want to see in future in addition to fixing this memory issue (which seems to be related to the https://github.com/appscode/kubed/pull/361 ).

**Comment by tamalsaha** [comment]
I would like to hear your feedback on https://github.com/appscode/kubed/issues/363 .

**Comment by tamalsaha** [comment]
I have released v0.11.0 https://github.com/appscode/kubed/releases/tag/v0.11.0 . Please give it a shot.

**Comment by r-divakaran-hrs** [comment]
I had the same issue. Upgraded kubed from version 0.9.o to 0.11.0 and the memory consumption has drastically reduced.

**Comment by estahn** [comment]
We have been running `chart: kubed-v0.11.0` and still see the same memory issues.

**Comment by tamalsaha** [comment]
This should be fixed in https://github.com/appscode/kubed/releases/tag/v0.12.0-rc.0 as I have removed everything except the config syncer. Please try it and if you still see this issue comment on https://github.com/appscode/kubed/issues/357 .
