### ISSUE TITLE
Kubed fails to start on initial start

### ISSUE THREAD

**Issue by n1koo** [appscode/kubed#316]
Similar to https://github.com/kubernetes/kubernetes/pull/67433 k8s since 1.10 (I think) properly answer 503 when the discovery endpoint for apiservice object is not reachable.

This blocks `kubed` from starting:

With `-v5`:

```
I1102 14:05:40.541517       1 audit.go:289] No audit policy file provided for AdvancedAuditing, no events will be recorded.
I1102 14:05:40.561950       1 request.go:1099] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I1102 14:05:40.569181       1 request.go:1099] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I1102 14:05:40.581752       1 request.go:1099] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I1102 14:05:40.589923       1 request.go:1099] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I1102 14:05:40.604751       1 request.go:1099] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I1102 14:05:40.614930       1 request.go:1099] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I1102 14:05:40.623093       1 request.go:1099] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I1102 14:05:40.631383       1 request.go:1099] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I1102 14:05:40.640813       1 request.go:1099] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I1102 14:05:40.650402       1 request.go:1099] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I1102 14:05:40.652434       1 operator.go:101] [configuring kubed ...]
I1102 14:05:40.680818       1 request.go:1099] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I1102 14:05:40.698746       1 request.go:1099] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
Error: unable to retrieve the complete list of server APIs: kubed.appscode.com/v1alpha1: the server is currently unable to handle the request
Usage:
  kubed run [flags]

Flags:
```

On `apiserver` this is apparent:

```
Nov  2 14:04:30 sa-kubemaster-1 hyperkube[13598]: I1102 14:04:30.358823   13598 controller.go:105] OpenAPI AggregationController: Processing item v1alpha1.kubed.appscode.com
Nov  2 14:04:32 sa-kubemaster-1 hyperkube[13598]: E1102 14:04:32.145652   13598 controller.go:111] loading OpenAPI spec for "v1alpha1.kubed.appscode.com" failed with: failed to retrieve openAPI spec, http error: ResponseCode: 503, Body: service unavailable
Nov  2 14:04:32 sa-kubemaster-1 hyperkube[13598]: , Header: map[Content-Type:[text/plain; charset=utf-8] X-Content-Type-Options:[nosniff]]
Nov  2 14:04:32 sa-kubemaster-1 hyperkube[13598]: I1102 14:04:32.145688   13598 controller.go:119] OpenAPI AggregationController: action for item v1alpha1.kubed.appscode.com: Rate Limited Requeue.
Nov  2 14:04:38 sa-kubemaster-1 hyperkube[13598]: E1102 14:04:38.629211   13598 memcache.go:134] couldn't get resource list for kubed.appscode.com/v1alpha1: the server is currently unable to handle the request
```

The workaround mentioned in https://github.com/kubernetes/kubernetes/issues/65005#issuecomment-397390513 also works here but needs a proper fix. 

Didn't spot anything in `master`, this should be breaking a lot of new installs on modern k8s versions.

**Comment by n1koo** [comment]
Seems like this is fixed in `master` , probably part of https://github.com/appscode/kubed/pull/314

Might just warrant a new release :)

**Comment by morganwalker** [comment]
We're having the same issue. @n1koo, https://github.com/kubernetes/kubernetes/issues/65005#issuecomment-397390513 didn't work for me. I also tried `curl -fsSL https://raw.githubusercontent.com/appscode/kubed/master/hack/deploy/kubed.sh | bash -s -- --uninstall --namespace=kubed` and that failed with the same errors. Am I missing something?

**Comment by tamalsaha** [comment]
Fixed by 0.9.0

**Comment by tamalsaha** [comment]
Please re-open if the issue is not fixed.

**Comment by loomsen** [comment]
This is not fixed for me. I'm unable to delete namespaces because of kubed.

```
$ k delete ns nvarz --grace-period=0 -v=7
I0320 21:29:36.865794   24335 loader.go:359] Config loaded from file /home/user/.kube/config
I0320 21:29:36.869938   24335 loader.go:359] Config loaded from file /home/user/.kube/config
I0320 21:29:36.872863   24335 round_trippers.go:416] GET https://<redacted>/apis/kubed.appscode.com/v1alpha1?timeout=32s
I0320 21:29:36.872907   24335 round_trippers.go:423] Request Headers:
I0320 21:29:36.872922   24335 round_trippers.go:426]     Accept: application/json, */*
I0320 21:29:36.872942   24335 round_trippers.go:426]     User-Agent: kubectl/v1.13.2 (linux/amd64) kubernetes/cff46ab
I0320 21:29:36.944513   24335 round_trippers.go:441] Response Status: 503 Service Unavailable in 71 milliseconds
I0320 21:29:36.987620   24335 request.go:1144] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I0320 21:29:36.987651   24335 cached_discovery.go:77] skipped caching discovery info due to the server is currently unable to handle the request
```
